services:
  frontend:
    build:
      context: ./frontend # Looks for Dockerfile in the ./frontend directory
    ports:
      - "${FRONTEND_PORT}:80" # Maps host:${FRONTEND_PORT} to container:80

  backend:
    build:
      context: ./backend # Looks for Dockerfile in the ./backend directory
    ports:
      - "${BACKEND_PORT}:4590" # Maps host:${BACKEND_PORT} to container:4590
